import { ExamData, Question } from '../firestoreTypes';

export const examData: ExamData = {
  id: 'toefl-exam-1',
  title: 'TOEFL模試 vol.1 (新構造版)', // タイトルを少し変更
  description: 'TOEFL iBT形式の模擬試験です。リーディングセクションのみ含まれています。',
  type: 'TOEFL',
  isFree: true,
  structure: [
    {
      type: 'instructions',
      title: '試験全体の指示',
      instructions: 'この模試はTOEFL iBTのリーディングセクションを模したものです。指示に従って問題を解いてください。'
    },
    {
      type: 'reading',
      title: 'Reading Section 1',
      duration: 18 * 60, // 1パッセージあたり18分目安 (10問)
      instructions: '最初のパッセージを読み、続く10個の質問に答えてください。'
      // passageId: 'passage-urban-birds' // 必要ならパッセージIDを指定
    },
    {
      type: 'reading',
      title: 'Reading Section 2',
      duration: 18 * 60,
      instructions: '2番目のパッセージを読み、続く10個の質問に答えてください。'
      // passageId: 'passage-silk-road'
    },
    // { type: 'listening', title: 'Listening Section', duration: 41 * 60, instructions: '...' },
    // { type: 'break', title: '休憩', duration: 10 * 60, instructions: '10分間の休憩です。' },
    // { type: 'speaking', title: 'Speaking Section', duration: 17 * 60, instructions: '...' },
    // { type: 'writing', title: 'Writing Section', duration: 50 * 60, instructions: '...' },
  ],
};

export const questions: Question[] = [
  // Reading Section 1 (Urban Birds)
  {
    id: 'toefl-exam-1-r1-01',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1', // 対応するstructureのtitle
    sectionType: 'reading',
    order: 1,
    content: 'What is the primary focus of the passage?',
    options: ['The benefits of urban green spaces for human recreation', 'The effects of urban development on bird populations and their adaptations', 'The history of bird migration patterns in North America', 'The role of pollution in shaping urban ecosystems'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  {
    id: 'toefl-exam-1-r1-02',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 2,
    content: 'According to the passage, what is one reason grassland bird species have declined in North America?',
    options: ['Increased competition from urban-adapted birds', 'Exposure to artificial light in cities', 'Conversion of farmland into suburban neighborhoods', 'Lack of suitable migratory routes'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  // ... (r1-03 から r1-10 まで同様に sectionTitle と order を追加) ...
  {
    id: 'toefl-exam-1-r1-03',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 3,
    content: 'The word "fragmentation" in paragraph 2 most nearly means:',
    options: ['Restoration', 'Division into smaller parts', 'Expansion', 'Contamination'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  {
    id: 'toefl-exam-1-r1-04',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 4,
    content: 'What is one effect of noise pollution mentioned in the passage?',
    options: ['It attracts more birds to urban areas.', "It interferes with birds' ability to communicate.", 'It increases the availability of nesting sites.', 'It reduces the toxicity of chemical runoff.'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
   {
    id: 'toefl-exam-1-r1-05',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 5,
    content: 'What can be inferred about birds like the House Sparrow from the passage?',
    options: ['They are unable to survive in rural environments.', 'They require specific nesting sites to thrive.', 'They benefit from human activity in cities.', 'They are more vulnerable to pollution than other species.'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  {
    id: 'toefl-exam-1-r1-06',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 6,
    content: 'The word "toll" in paragraph 4 most nearly means:',
    options: ['Damage', 'Benefit', 'Measurement', 'Collection'],
    correctAnswer: 0,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  {
    id: 'toefl-exam-1-r1-07',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 7,
    content: 'What is one finding from the study in London mentioned in the passage?',
    options: ['Urban birds have lower stress levels than rural birds.', 'Birds near busy roads lay fewer eggs.', 'Green spaces in London support no rare species.', 'Pollution has no effect on urban bird reproduction.'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  {
    id: 'toefl-exam-1-r1-08',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 8,
    content: 'Why does the author mention the collisions of migrating birds with skyscrapers?',
    options: ['To illustrate a benefit of urban expansion', 'To provide an example of a threat caused by light pollution', 'To argue that skyscrapers should be banned', 'To explain why nocturnal birds thrive in cities'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  {
    id: 'toefl-exam-1-r1-09',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 9,
    content: 'What can be inferred about the effectiveness of small urban parks?',
    options: ['They are as effective as large parks in supporting bird diversity.', 'They provide limited benefits compared to larger green spaces.', 'They attract more migratory birds than rural areas.', 'They are primarily used by nocturnal species.'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },
  {
    id: 'toefl-exam-1-r1-10',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 10,
    content: "The author's attitude toward urban planning solutions for bird conservation can best be described as:",
    options: ['Skeptical', 'Indifferent', 'Critical', 'Optimistic'],
    correctAnswer: 3,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r1.png?alt=media&token=318fb20b-d237-4a26-9c34-682078e8aa16',
  },

  // Reading Section 2 (Silk Road)
  {
    id: 'toefl-exam-1-r2-01', // IDを変更
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2', // 対応するstructureのtitle
    sectionType: 'reading',
    order: 1, // Section 2 内での順序
    content: 'What is the main purpose of the passage?',
    options: ["To argue that the Silk Road was the most important trade route in history", "To describe the rise, impact, and decline of the Silk Road", "To explain how maritime trade replaced all land-based routes", "To criticize the Mongol Empire's role in global trade"],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-02',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 2,
    content: "According to the passage, what was one role of the Han Dynasty in the Silk Road's development?",
    options: ['It invented silk production techniques', 'It sent emissaries to establish trade with Central Asia', 'It built sea routes to Europe', 'It prevented cultural exchanges with other regions'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  // ... (r2-03 から r2-10 まで同様に sectionTitle と order を追加) ...
    {
    id: 'toefl-exam-1-r2-03',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 3,
    content: 'The word "coveted" in paragraph 2 most nearly means:',
    options: ['Disliked', 'Desired', 'Produced', 'Traded'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-04',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 4,
    content: 'What is one example of cultural exchange mentioned in the passage?',
    options: ['The spread of Buddhism from India to China', 'The invention of silk in Rome', 'The construction of caravanserais in Europe', 'The decline of trade due to disease'],
    correctAnswer: 0,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-05',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 5,
    content: 'What can be inferred about the Pax Mongolica from the passage?',
    options: ['It caused the permanent decline of the Silk Road', 'It was a time of instability and war', 'It provided a period of safety that boosted trade', 'It limited cultural diffusion across Asia'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-06',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 6,
    content: 'The word "eroded" in paragraph 5 most nearly means:',
    options: ['Strengthened', 'Weakened', 'Expanded', 'Improved'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-07',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 7,
    content: 'Why does the author mention the development of maritime technologies in the 15th century?',
    options: ["To show how they supported the Silk Road's growth", "To explain a reason for the Silk Road's decline", 'To argue that land routes were more efficient', "To highlight the Mongol Empire's naval power"],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-08',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 8,
    content: "According to the passage, what was one environmental factor that contributed to the Silk Road's decline?",
    options: ['The spread of the bubonic plague', 'The construction of new trade cities', 'Prolonged droughts in Central Asia', 'The introduction of gunpowder'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-09',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 9,
    content: "What can be inferred about the Silk Road's legacy from the passage?",
    options: ['It had no lasting impact on global trade', 'It influenced modern efforts to connect Eurasia', 'It was quickly forgotten after its decline', 'It only benefited the Mongol Empire'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
  {
    id: 'toefl-exam-1-r2-10',
    examId: 'toefl-exam-1',
    sectionTitle: 'Reading Section 2',
    sectionType: 'reading',
    order: 10,
    content: "The author's attitude toward the Silk Road's historical significance can best be described as:",
    options: ['Skeptical', 'Admiring', 'Dismissive', 'Neutral'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-1-r2.png?alt=media&token=c116d357-cdcd-4a7f-8d92-33dab5f288df',
  },
]; 