import { ExamData, Question, ExamSection } from '../firestoreTypes'; // 型定義をインポート

// 模試定義 (ExamData)
export const examData: Omit<ExamData, 'id' | 'createdAt' | 'updatedAt'> = {
  title: 'TOEFL模試 vol.2',
  description: 'TOEFL形式の模擬試験です。',
  type: 'TOEFL',
  isFree: true,
  // price: 1500, // isFree: false の場合
  structure: [
    { 
      type: 'instructions', 
      title: '試験開始前の指示', 
      instructions: 'この試験はリーディングセクションのみで構成されています。準備ができたら「次へ進む」をクリックしてください。' 
    },
    { 
      type: 'reading', 
      title: 'Reading Section 1', 
      duration: 3600, // 例: 60分
      instructions: '以下のパッセージを読み、設問に答えてください。' 
    },
    // 必要に応じて他のセクション (Listening, Speaking, Writing, Break など) を追加
  ],
};

// 問題リスト (Question[])
export const questions: Omit<Question, 'id' | 'examId'>[] = [
  // Reading Section 1 の問題 (seed-exams.ts から移行)
  {
    sectionTitle: 'Reading Section 1', 
    sectionType: 'reading',
    order: 1,
    content: 'What is the primary purpose of the passage?',
    options: ['To argue for the protection of all species in ecosystems', 'To explain the significance of keystone species in maintaining ecosystem balance', 'To describe the history of ecological research', 'To compare different types of ecosystems'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 2,
    content: 'According to the passage, what happens when sea otters are removed from kelp forest ecosystems?',
    options: ['Sea urchins disappear due to lack of food', 'Kelp forests expand rapidly', 'The ecosystem experiences a trophic cascade', 'Fish populations increase immediately'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 3,
    content: 'The author mentions elephants in the African savanna primarily to illustrate:',
    options: ['The destructive impact of large herbivores', 'How keystone species can modify their habitats', 'The competition between grazing animals', 'The decline of biodiversity in grasslands'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 4,
    content: 'The term "ecosystem engineers" in the passage refers to species that:',
    options: ['Control prey populations', 'Create or alter habitats', 'Depend on specific plants for survival', 'Prevent trophic cascades'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 5,
    content: 'What can be inferred about the reintroduction of wolves in Yellowstone National Park?',
    options: ['It had no effect on elk populations', 'It restored balance to the ecosystem', 'It caused an immediate decline in biodiversity', 'It led to the extinction of beavers'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    // 注意: seed-exams.ts では末尾に 6 が付いていたが、他の画像と合わせるため削除
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769', 
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 6,
    content: 'The word "proliferate" in the passage is closest in meaning to:',
    options: ['Decrease', 'Spread', 'Increase rapidly', 'Compete'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 7,
    content: 'Why does the author discuss the decline of keystone species like tigers?',
    options: ['To highlight the challenges of identifying keystone species', 'To show the broader consequences of human activities', 'To suggest that prey species are more important', 'To argue against conservation efforts'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 8,
    content: 'Which of the following is NOT mentioned as a threat to keystone species?',
    options: ['Habitat destruction', 'Climate change', 'Overhunting', 'Invasive species'],
    correctAnswer: 3,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 9,
    content: "The author's attitude toward conservation efforts targeting keystone species can best be described as:",
    options: ['Skeptical', 'Supportive', 'Dismissive', 'Uncertain'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 10,
    content: 'What does the passage imply about the identification of keystone species?',
    options: ['It is a simple process based on population size', 'It is often only clear after their removal', 'It depends entirely on their predatory behavior', 'It is irrelevant to ecosystem management'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r1.png?alt=media&token=c1234569-c0ba-43d4-a618-493b1bf44769',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 11,
    content: 'What is the main purpose of the passage?',
    options: ['To compare large and small economies in global trade', 'To explore the effects of global trade on small economies', 'To criticize the policies of small economies', 'To advocate for the elimination of trade agreements'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 12,
    content: 'According to the passage, how have countries like Singapore and Luxembourg benefited from global trade?',
    options: ['By relying on natural resource exports', 'By exporting specialized goods and services', 'By avoiding trade agreements', 'By increasing domestic production costs'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 13,
    content: 'The author mentions the 2020 pandemic primarily to illustrate:',
    options: ['The resilience of small economies', 'The vulnerability of small economies to external shocks', 'The importance of diversified industries', 'The benefits of tourism revenue'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 14,
    content: 'The term "economies of scale" in the passage refers to:',
    options: ['The ability of small economies to compete globally', 'The cost advantages of large-scale production', 'The diversification of export goods', 'The negotiation power of trade blocs'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    // 注意: seed-exams.ts では末尾に f が付いていたが、他の画像と合わせるため削除
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25', 
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 15,
    content: "What can be inferred about Botswana's economic strategy from the passage?",
    options: ['It has focused solely on diamond exports', 'It has reduced its participation in global trade', 'It has broadened its economic base to reduce risk', 'It has avoided regional trade agreements'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 16,
    content: 'The word "exacerbate" in the passage is closest in meaning to:',
    options: ['Improve', 'Worsen', 'Balance', 'Ignore'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 17,
    content: 'Why does the author discuss regional trade blocs like CARICOM?',
    options: ['To show how they increase dependency on large economies', 'To argue that they are ineffective for small economies', 'To demonstrate a strategy for enhancing competitiveness', 'To highlight their role in reducing export diversity'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 18,
    content: 'Which of the following is NOT mentioned as a challenge for small economies in global trade?',
    options: ['Economic dependency', 'Unequal competition', 'Limited natural resources', 'Political instability'],
    correctAnswer: 3, // Political instability は直接言及されていない
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 19,
    content: "The author's attitude toward strategic policymaking in small economies can best be described as:",
    options: ['Skeptical', 'Neutral', 'Supportive', 'Pessimistic'],
    correctAnswer: 2,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
  {
    sectionTitle: 'Reading Section 1',
    sectionType: 'reading',
    order: 20,
    content: 'What does the passage suggest about the future of small economies in global trade?',
    options: ['They will inevitably decline due to competition', 'Their success depends on adapting to global demands', 'They should focus only on domestic markets', 'They are unaffected by larger economies'],
    correctAnswer: 1,
    questionType: 'multiple-choice',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/toremock.firebasestorage.app/o/toefl-exam-2-r2.png?alt=media&token=760a564f-2aa7-4cbf-aa6b-d2c15e6e7c25',
  },
]; 